RECURSIVE originS umount + Relocate /s zfs to be under /root (to support non-zfs_jail..) + HACK to try using jails from jailed templates from root...

diff --git a/iocage b/iocage
--- a/iocage
+++ b/iocage
@@ -521,9 +521,7 @@ __create_jail () {
 	zfs snapshot $pool/ioc/r/$release/root@$uuid
 	zfs snapshot $pool/ioc/r/$release/skel@$uuid
 	zfs clone $pool/ioc/r/$release/root@$uuid tank/ioc/j/$uuid/root
-        zfs clone $pool/ioc/r/$release/skel@$uuid tank/ioc/j/$uuid/s
-	zfs set mountpoint=none tank/ioc/j/$uuid/s
-	zfs set readonly="on" tank/ioc/j/$uuid/root
+        zfs clone $pool/ioc/r/$release/skel@$uuid tank/ioc/j/$uuid/root/s
     else
         zfs snapshot -r $pool/ioc/r/$release@$uuid
         zfs send     -R $pool/ioc/r/$release@$uuid | \
@@ -540,14 +538,14 @@ __create_jail () {
 
     # at create time set the default rc.conf
     if [ "${2}" = "-s" ] ; then
-	mount -t zfs tank/ioc/j/${uuid}/s /ioc/j/${uuid}/root/s
-
         # echo "hostname=${uuid}" > /ioc/j/${uuid}/root/etc/rc.conf
         __jail_rc_conf >> \
         /ioc/j/${uuid}/root/etc/rc.conf
         __resolv_conf > /ioc/j/${uuid}/root/etc/resolv.conf
 
-	umount tank/ioc/j/${uuid}/s
+	zfs set readonly="on" tank/ioc/j/$uuid/root
+	zfs set readonly="off" tank/ioc/j/$uuid/root/s
+	zfs set mountpoint=none tank/ioc/j/$uuid/root/s
     elif [ "${2}" != "-e" ] ; then
         echo "hostname=${uuid}" > /ioc/j/${uuid}/root/etc/rc.conf
         __jail_rc_conf >> \
@@ -558,6 +556,7 @@ __create_jail () {
     fi
 
     zfs create ${pool}/$jail_zfs_dataset
+    zfs set readonly="off" tank/ioc/j/$uuid/root/data
     zfs set mountpoint=none ${pool}/$jail_zfs_dataset
 
     if [ "$jail_zfs_hostonly" != "on" ] ; then
@@ -584,8 +583,15 @@ __clone_jail () {
     local dataset="$(__find_jail $name)"
 
     if [ -z $dataset ] ; then
-        echo "  ERROR: $name not found"
-        exit 1
+	# HACK: "Forget" mypool_file and try again...
+	local real_pool=$pool
+	export pool="tank"
+	local dataset=$(__find_jail $name)
+	export pool=$real_pool
+        if [ -z $dataset ] ; then
+            echo "  ERROR: $name not found"
+            exit 1
+	fi
     fi
 
     if [ $dataset == "multiple" ] ; then
@@ -652,7 +658,7 @@ __destroy_jail () {
         exit 1
     fi
 
-    local origin="$(zfs get -H -o value origin $dataset)"
+    local fs_list="$(zfs list -rH -o name $dataset)"
     local fulluuid="$(__check_name $name)"
     local state="$(jls | grep ${fulluuid} | wc -l)"
 
@@ -665,14 +671,26 @@ __destroy_jail () {
 
     if [ "$answer" == "Y" ] && [ "$state" -lt "1" ] ; then
         echo "  Destroying: $fulluuid"
+
+	local origins=""
+	for fs in $fs_list ; do
+	    local origin="$(zfs get -H -o value origin $fs)"
+
+            if [ "$origin" != "-" ] ; then
+		#zfs destroy -r $origin
+		local origins=$(echo $origins; echo $origin)
+            fi
+	done
+
+
+	echo "  Destroying Dataset: $dataset"
         zfs destroy -fr $dataset
 
-        # TODO: DESTROY /ioc/r/$release@$uuid if it exist.
+	for origin in $origins ; do
+	    echo "  Destroying clone origin: $origin"
+	    zfs destroy -r $origin
+	done
 
-        if [ "$origin" != "-" ] ; then
-            echo "  Destroying clone origin: $origin"
-            zfs destroy -r $origin
-        fi
 
     elif [ "$state" -gt "0" ] ; then
         echo "  ERROR: Jail is up and running ..exiting"
@@ -1006,6 +1024,13 @@ __start_jail () {
         fi
         zfs mount ${pool}/ioc/j/${fulluuid}/root
     fi
+    state="$(zfs list | grep "${fulluuid}/root/s" | wc -l)"
+    if [ ! "$state" -eq "0" ] ; then
+	state="$(mount | grep "${fulluuid}/root/s" | wc -l)"
+	if [ "$state" -eq "0" ] ; then
+            zfs mount ${pool}/ioc/j/${fulluuid}/root/s
+	fi
+    fi
 
     if [ "$procfs" == "1" ] ; then
         mount -t procfs proc /ioc/j/${fulluuid}/root/proc
@@ -1015,7 +1040,7 @@ __start_jail () {
     local jzfs_dataset="$(__get_jail_prop jail_zfs_dataset $fulluuid)"
     local jzfs_hostonly="$(__get_jail_prop jail_zfs_hostonly $fulluuid)"
     local jzfs_fstab=/ioc/j/${fulluuid}/zfstab
-    local jzfs_sfs=tank/ioc/j/${fulluuid}/s
+    local jzfs_sfs=tank/ioc/j/${fulluuid}/root/s
 
     if [ $jzfs == "on" ] ; then
         __set_jail_prop allow_mount=1 $fulluuid
@@ -1082,6 +1107,8 @@ __start_jail () {
     if [ ! "$state" -eq "0" ] ; then
 	zfs set jailed=on $jzfs_sfs
 	zfs jail ioc-${fulluuid} $jzfs_sfs
+
+	# TODO: ONLY IF jail_zfs IS ON... Otherwise HOST must mount it for us..
 	jexec ioc-${fulluuid} mount -t zfs $jzfs_sfs /s
 
 	# TODO REVIEW THIS AND MAKE IT OPTIONAL...
@@ -1311,7 +1338,7 @@ __stop_jail () {
     umount /ioc/j/${fulluuid}/root/proc   > /dev/null 2>&1
 
     # FORCE UNMOUNT DATASET AND CHILD(s)...
-    local fs_list="$(zfs list -rH -o name $dataset)"
+    local fs_list="$(mount | grep "${fulluuid}" | awk '{print $3}')"
     for fs in $fs_list ; do
         umount -f $fs > /dev/null 2>&1
     done
@@ -1426,7 +1453,7 @@ __list_jails () {
     local jails=$(__find_jail ALL)
     local switch=$1
 
-    printf "%-13s  %s  %s  %s  %s\n" "UUID" "HOSTNAME" "BOOT"\
+    printf "%-13s  %-13s  %s  %s  %s\n" "UUID" "HOSTNAME" "BOOT"\
            "STATE" "TAG"
     for jail in $jails ; do
         uuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
@@ -1450,12 +1477,12 @@ __list_jails () {
 	# TODO: elif case for "-s" SINKs...
         if [ $switch == "-t" ] ; then
             if [ $template == "yes" ] ; then
-                printf "%-+.36s  %-8s  %-3s   %-4s   %s\n" "$uuid" "$hostname"\
+                printf "%-+.13s  %-13s  %-3s   %-4s   %s\n" "$uuid" "$hostname"\
                 "$boot" "$state" "$tag"
             fi
         elif [ $switch != "-t" ] ; then
             if [ $template != "yes" ] ; then
-                printf "%-+.36s  %-8s  %-3s   %-4s   %s\n" "$uuid" "$hostname"\
+                printf "%-+.13s  %-13s  %-3s   %-4s   %s\n" "$uuid" "$hostname"\
                 "$boot" "$state" "$tag"
             fi
         fi
