PULL WIP..

diff --git a/lib/ioc-sync b/lib/ioc-sync
--- a/lib/ioc-sync
+++ b/lib/ioc-sync
@@ -11,6 +11,17 @@ __pull () {
     # TODO: use zfs properties to save ssh_host and ssh_port options
     #       and make 2nd and 3rd arg optional.
 
+    local _sink=__find_sink $_uuid
+
+    if [ -z $_sink ]; then
+	echo "SINK NOT FOUND"
+	exit 1
+    fi
+
+    echo "SINK: $_sink"
+    
+    local _snapshots="$(zfs list -rH -d0 -o name -t snapshot $_sink)"
+    echo "$s_snapshots"
 }
 
 
