Super Jails WIP..

diff --git a/lib/ioc-zfs b/lib/ioc-zfs
--- a/lib/ioc-zfs
+++ b/lib/ioc-zfs
@@ -147,32 +147,32 @@ __reclone_basejail () {
 # This creates jails----------------------------------------------------
 __create_jail () {
     local _installed _releases _zfsconfig _supported_release _configured \
-          _zfsconfig
+          _zfsconfig _super
 
     _installed=$(zfs list -r ${pool}${iocroot}/releases|grep $release)
     _releases=$(__list_jails -r|grep -v "Downloaded releases:")
-    _supported_release=$(echo "$release" | grep "RELEASE")
+#    _supported_release=$(echo "$release" | grep "RELEASE")
     _zfsconfig="$(__configure_jail generate)"
 
     _configured="0"
 
-    if [ -z "$_supported_release" ] ; then
-        echo "  You are not running a RELEASE."
-        echo "  ERROR: Please specify release=RELEASE."
-        exit 1
-    fi
+#    if [ -z "$_supported_release" ] ; then
+#        echo "  You are not running a RELEASE."
+#        echo "  ERROR: Please specify release=RELEASE."
+#        exit 1
+#    fi
 
-    if [ -z "$_installed" -a -z "$_releases" ] ; then
-        echo "  ERROR: No RELEASEs found locally, run iocage fetch first."
-        exit 1
-    elif [ -z "$_installed" ] ; then
-        echo "  RELEASE $release not found locally."
-        echo "  Please fetch $release or rerun iocage with release=RELEASE"
-        echo ""
-        echo "  These are the releases you have already fetched:"
-        echo "  $_releases"
-        exit 1
-    fi
+#    if [ -z "$_installed" -a -z "$_releases" ] ; then
+#        echo "  ERROR: No RELEASEs found locally, run iocage fetch first."
+#        exit 1
+#    if [ -z "$_installed" ] ; then
+#        echo "  RELEASE $release not found locally."
+#        echo "  Please fetch $release or rerun iocage with release=RELEASE"
+#        echo ""
+#        echo "  These are the releases you have already fetched:"
+#        echo "  $_releases"
+#        exit 1
+#    fi
 
     if [ "${2}" = "-c" ] ; then
         fs_list=$(zfs list -rH -o name ${pool}${iocroot}/releases/$release)
@@ -204,6 +204,26 @@ __create_jail () {
                   $iocroot/jails/$uuid/root/$dir
         done
         _configured="1"
+    elif [ "${2}" = "-s" ] ; then
+        export type=superjail
+        zfs snapshot -r ${pool}${iocroot}/super@$uuid
+        eval "zfs create -p ${_zfsconfig} \"${pool}${iocroot}/jails/$uuid\""
+        __set_jail_prop type=superjail ${uuid}
+
+	zfs clone -o readonly=on \
+	${pool}${iocroot}/super/${super}/mroot@$uuid \
+	${pool}${iocroot}/jails/$uuid/root
+
+        zfs clone \
+	${pool}${iocroot}/super/${super}/skel@$uuid \
+	${pool}${iocroot}/jails/$uuid/s
+	for fs in $sfs_list ; do
+            zfs clone \
+	    ${pool}${iocroot}/super/${super}/skel/$fs@$uuid \
+	    ${pool}${iocroot}/jails/$uuid/s/$fs
+	done	
+	zfs create ${pool}${iocroot}/jails/$uuid/s/tmp
+	_configured="1"
     else
         zfs snapshot -r ${pool}${iocroot}/releases/$release@$uuid
         zfs send     -R ${pool}${iocroot}/releases/$release@$uuid | \
@@ -223,20 +243,20 @@ __create_jail () {
 
     # at create time set the default rc.conf
     if [ "${2}" != "-e" ] ; then
-        echo "hostname=\"${hostname}\"" > $iocroot/jails/${uuid}/root/etc/rc.conf
+        echo "hostname=\"${hostname}\"" > $iocroot/jails/${uuid}/s/etc/rc.conf
         __jail_rc_conf >> \
-        $iocroot/jails/${uuid}/root/etc/rc.conf
-        __resolv_conf ${uuid} > $iocroot/jails/${uuid}/root/etc/resolv.conf
+        $iocroot/jails/${uuid}/s/etc/rc.conf
+        __resolv_conf ${uuid} > $iocroot/jails/${uuid}/s/etc/resolv.conf
     elif [ "${2}" = "-e" ] ; then
         echo $uuid
     fi
 
-    zfs create -o compression=lz4 ${pool}/$jail_zfs_dataset
-    zfs set mountpoint=none ${pool}/$jail_zfs_dataset
-    zfs set jailed=on ${pool}/$jail_zfs_dataset
-
+    zfs create -o compression=lz4 ${pool}${iocroot}${jail_zfs_dataset}
+    zfs set mountpoint=none ${pool}${iocroot}${jail_zfs_dataset}
+    zfs set jailed=on ${pool}${iocroot}${jail_zfs_dataset}
+    
     # configure the jail mountpoint
-    __hack88_mount ${uuid}
+#    __hack88_mount ${uuid}
 
     # Install extra packages
     # this requires working resolv.conf in jail
