WIP..

diff --git a/lib/ioc-sync b/lib/ioc-sync
--- a/lib/ioc-sync
+++ b/lib/ioc-sync
@@ -11,17 +11,32 @@ __pull () {
     # TODO: use zfs properties to save ssh_host and ssh_port options
     #       and make 2nd and 3rd arg optional.
 
+    local _jail="$(__find_jail $_uuid)"
     local _sink="$(__find_sink $_uuid)"
 
+    if [ -z $_jail ]; then
+	echo "JAIL NOT FOUND"
+	exit 1
+    fi
     if [ -z $_sink ]; then
 	echo "SINK NOT FOUND"
 	exit 1
     fi
-
-    echo "SINK: $_sink"
     
-    local _snapshots="$(zfs list -t snapshot | grep -E "^${pool}${iocroot}/sinks/[a-zA-Z0-9]{8,}*-*.[a-zA-Z0-9]{4,}@")"
-    echo "$_snapshots"
+    local _snapshot="$(date "+%F-%T")"
+    local _zfs_snapshots="$(zfs list -H -t snapshot -o name)"
+
+    local _sink_snapshots="$(echo $_zfs_snapshots | grep -E "^${pool}${iocroot}/sinks/$_uuid/root/s@")"
+    echo "$_sink_snapshots"
+
+    local _jail_snapshots="$(echo $_zfs_snapshots | grep -E "^${pool}${iocroot}/jails/$_uuid/root/s@")"
+    echo "$_jail_snapshots"
+
+    local _jailsnap=$(echo $_jail_snapshots | tail -n 1)
+    local _sinksnap=$(echo $_sink_snapshots | tail -n 1)
+
+    zfs snapshot -r $_jail/root/s@$_snapshot
+    zfs send -RI $_jailsnap $_jail/root/s@_snapshot | zfs recv -vF $_sink/root/s
 }
 
 
